# vim: set sw=2 ts=2 softtabstop=2 expandtab:
language: csharp
os: linux
dist: bionic
dotnet: 3.1
mono: none
git:
  depth: false
env:
  global:
    - SOLUTION=Source/Boogie.sln
    - Z3URL=https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04.zip
    - BOOGIE_GITVERSION=1
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
install:
  # Download a Z3 release
  - wget ${Z3URL}
  - unzip z3*.zip
  - export PATH="$(find $PWD/z3* -name bin -type d):$PATH"
  # Install python tools
  - sudo pip install lit OutputCheck pyyaml psutil
  # Restore dotnet tools
  - dotnet tool restore
script:
  # Check that generated scanner and parser are consistent with attributed grammar
  - dotnet tool run coco Source/Core/BoogiePL.atg -namespace Microsoft.Boogie -frames Source/Core/
  - diff --strip-trailing-cr Source/Core/Parser.cs Source/Core/Parser.cs.old
  - diff --strip-trailing-cr Source/Core/Scanner.cs Source/Core/Scanner.cs.old
  # Build Boogie
  - dotnet pack -c ${CONFIGURATION} ${SOLUTION}
  # Run unit tests
  - dotnet test -c ${CONFIGURATION} ${SOLUTION}
  # Run lit test suite
  - lit -v --timeout=120 -D configuration=${CONFIGURATION} Test
  # Do not deploy if GitVersionTask could not be used to extract the correct version number
  - test ! -e Source/BoogieDriver/bin/${CONFIGURATION}/Boogie.1.0.0.nupkg
deploy:
  - provider: script
    script: dotnet nuget push "Source/**/bin/${CONFIGURATION}/Boogie*.nupkg" -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$
  - provider: releases
    name: $TRAVIS_TAG
    token:
      secure: ZjKhOiIpC6R+Xfp1iJX/1a2DD1o+tYhUefZDqRjUfM4rDZqzvOBvY7mA/1BcqNs4gXJIk3p11Kud72cPSSS8iW2EVlRm2UlfdVOf2wmGys/TILvHNDWUoVFSxhVgxbzMVULp6fIrqDypaZ0PAYZVg2loLkVI5AZ/P35ZRVaa9oE=
    file_glob: true
    file: Source/BoogieDriver/bin/${CONFIGURATION}/Boogie*.nupkg
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$
