# vim: set sw=2 ts=2 softtabstop=2 expandtab:
language: csharp
os: linux
dist: bionic
dotnet: 3.1
mono: none
git:
  depth: false
env:
  global:
    - SOLUTION=Source/Boogie-NetCore.sln
    - Z3URL=https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-ubuntu-16.04.zip
    # Workaround for GitVersionTask bug in combination with .NET Core SDK 3.1.200
    # (see, e.g., https://github.com/dotnet/sdk/issues/10878 and https://github.com/GitTools/GitVersion/issues/2063)
    - MSBUILDSINGLELOADCONTEXT=1
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
install:
  # Download a Z3 release
  - wget ${Z3URL}
  - unzip z3*.zip
  - export PATH="$(find $PWD/z3* -name bin -type d):$PATH"
  # Install needed python tools
  - sudo pip install lit OutputCheck pyyaml
script:
  - dotnet build -c ${CONFIGURATION} ${SOLUTION}
  - dotnet test --no-build -c ${CONFIGURATION} ${SOLUTION}
  - lit -v -D dotnet -D configuration=${CONFIGURATION} Test
  # Do not deploy if GitVersionTask could not be used to extract the correct version number
  - test ! -e Source/BoogieDriver/bin/${CONFIGURATION}/Boogie.1.0.0.nupkg
deploy:
  - provider: script
    script: dotnet nuget push Source/BoogieDriver/bin/${CONFIGURATION}/Boogie*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$
  - provider: releases
    name: $TRAVIS_TAG
    token:
      secure: ZjKhOiIpC6R+Xfp1iJX/1a2DD1o+tYhUefZDqRjUfM4rDZqzvOBvY7mA/1BcqNs4gXJIk3p11Kud72cPSSS8iW2EVlRm2UlfdVOf2wmGys/TILvHNDWUoVFSxhVgxbzMVULp6fIrqDypaZ0PAYZVg2loLkVI5AZ/P35ZRVaa9oE=
    file_glob: true
    file: Source/BoogieDriver/bin/${CONFIGURATION}/Boogie*.nupkg
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$
